- name: install maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: maven package
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Installing mysql client and load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql.schema

- name: start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup