- name: check roboshop user exist or not
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true

- when: output.rc != 0
  name: create roboshop user
  become: yes
  ansible.builtin.user:
    name: roboshop 

- name: /app directory exists or not
  ansible.builtin.stat:
    path: /app
  register: directory

- name: print the directory stats
  ansible.builtin.debug:
    msg: "output is: {{directory}}"

- name: crate a directory if directory doesn't exist
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == False

- name: "download {{component}} artifact"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: extract {{component}} atrifact
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes